перенес верстку категории шузов
pbuzdin/adidas-shop-frontend pull request #1
Opened 2017-05-11 18:40 UTC by pbuzdin

Компоненты пока не трогал

2017-05-11 21:59 UTC, imevro requested changes
Избавляйся от внешних ресурсов и поправь цсс

2017-05-11 21:59 UTC, evgenyrodionov commented on 2/src/ShoesCategory.css
> +
Чё тут за лошадиные отступы и почему 4 пробела вместо двух

2017-05-11 21:59 UTC, evgenyrodionov commented on 2/src/ShoesCategory.css
> +            src: url("https://p.burstingland.com/kurskurskurs/fonts/avenir-next-bold.woff");
Положи локально в проект

2017-05-11 21:59 UTC, evgenyrodionov commented on 2/src/ShoesCategory.js
> +                  <img src="http://dev.iboong.com/adidas-shop-frontend/1/img/filter.png" srcSet="http://dev.iboong.com/adidas-shop-frontend/1/img/filter@2x.png 2x, http://dev.iboong.com/adidas-shop-f
Тоже локально в проект

2017-05-12 00:57 UTC, pbuzdin commented on 2/src/ShoesCategory.css
> +
Пофиксил

2017-05-12 00:57 UTC, pbuzdin commented on 2/src/ShoesCategory.css
> +            src: url("https://p.burstingland.com/kurskurskurs/fonts/avenir-next-bold.woff");
Положил.

2017-05-12 00:57 UTC, pbuzdin commented on 2/src/ShoesCategory.js
> +                  <img src="http://dev.iboong.com/adidas-shop-frontend/1/img/filter.png" srcSet="http://dev.iboong.com/adidas-shop-frontend/1/img/filter@2x.png 2x, http://dev.iboong.com/adidas-shop-f
Все картинки тоже положил.

2017-05-12 01:08 UTC, pbuzdin commented
@evgenyrodionov все пофиксил

2017-05-12 10:10 UTC, evgenyrodionov commented
Коммиты на английском должны быть

2017-05-12 10:11 UTC, imevro approved these changes
Норм, только пофикси

2017-05-12 10:11 UTC, evgenyrodionov commented on 2/src/ShoesCategory/index.js
> +    return (
Поч тут 4 пробела-то

2017-05-12 10:11 UTC, evgenyrodionov commented on 2/src/ShoesCategory/index.js
> +    return (
Поставь преттир и всё

2017-05-12 10:11 UTC, evgenyrodionov commented on 2/src/ShoesCategory/style.css
> +  -moz-box-sizing: border-box;
В кра есть автопрефиксер, убирай отсюда

2017-05-12 10:12 UTC, merged

2017-05-12 10:33 UTC, pbuzdin commented on 2/src/ShoesCategory/style.css
> +  -moz-box-sizing: border-box;
пофиксил https://github.com/pbuzdin/adidas-shop-frontend/commit/df1a34f47c09dad06e69f84a577d814a5b911bf3

2017-05-12 10:44 UTC, pbuzdin commented on 2/src/ShoesCategory/index.js
> +    return (
пофиксил https://github.com/pbuzdin/adidas-shop-frontend/commit/16b63c8505bd2bfeb228a7b4433f98c8176c4501