Add more components
pbuzdin/adidas-shop-frontend pull request #2
Opened 2017-05-12 20:50 UTC by pbuzdin

2017-05-12 22:07 UTC, imevro requested changes
1) форматирование — откуда 4 пробела берутся?
2) правила импортов http://telegra.ph/6a640335-fcfd-4e53-b0d9-25cd145cb565-05-12
3) сетка на флоатах? Откуда? Мы делали на флексбоксах
4) зачем лишний импорт реакт-дом постоянно?
5) про структуру http://telegra.ph/6a640335-fcfd-4e53-b0d9-25cd145cb565-05-12

2017-05-12 22:07 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Content/Card.js
> +import SaleBadge from './SaleBadge';
Про правила импортов http://telegra.ph/6a640335-fcfd-4e53-b0d9-25cd145cb565-05-12

2017-05-12 22:07 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Content/Filter.js
> +//import ReactDOM from 'react-dom';
?

2017-05-12 22:07 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Content/Card.js
> +//import ReactDOM from 'react-dom';
?

2017-05-12 22:07 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Content/SaleBadge.js
> +    <SaleBadge>sale</SaleBadge>
Если он sale, то зачем компонент? Ты либо делай абстрактный Badge, либо сразу экспорти один компонент

2017-05-12 22:07 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Sidebar/Logo.js
> +    return (
Откуда 4 пробела

2017-05-13 01:13 UTC, pbuzdin commented on 2/src/ShoesCategory/Content/Card.js
> +//import ReactDOM from 'react-dom';
удалил

2017-05-13 01:15 UTC, pbuzdin commented on 2/src/ShoesCategory/Content/Filter.js
> +//import ReactDOM from 'react-dom';
удалил

2017-05-13 01:17 UTC, pbuzdin commented on 2/src/ShoesCategory/Content/SaleBadge.js
> +    <SaleBadge>sale</SaleBadge>
Пофиксил

2017-05-13 02:09 UTC, pbuzdin commented
Все поправил.

С импортом лишний раз я стиль дергаю, верно?

Роутер прикрутил, работает.

2017-05-13 10:00 UTC, imevro requested changes
Увидел что сетка на флоатах, не стал дальше проверять. Нету "все поправил".

2017-05-13 10:00 UTC, evgenyrodionov commented on 2/src/ShoesCategory/Content/img/filter.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120.3 100.3">
Что тут с форматированием?

2017-05-13 10:01 UTC, evgenyrodionov commented
Плюс выкинуть директории 1 и 2, сделать нормально

2017-05-13 11:51 UTC, pbuzdin commented
@evgenyrodionov на чем должна быть сетка?

2017-05-13 11:51 UTC, evgenyrodionov commented
На флекбоксах, сказал же

2017-05-13 11:54 UTC, pbuzdin commented
@evgenyrodionov Без адаптива можно?

2017-05-13 11:54 UTC, evgenyrodionov commented
Да

2017-05-13 12:14 UTC, pbuzdin commented
@evgenyrodionov добавил флексбокс грид

2017-05-13 12:57 UTC, imevro requested changes
Фикси

2017-05-13 12:57 UTC, evgenyrodionov commented on src/ShoesCategory/Content/img/filter.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120.3 100.3">
что с форматом

2017-05-13 12:57 UTC, evgenyrodionov commented on src/ShoesCategory/Content/index.js
> +import Card from './Card';
зачем

2017-05-13 12:57 UTC, evgenyrodionov commented on src/ShoesCategory/style.css
> +.row {
Из нпма

2017-05-13 18:48 UTC, imevro requested changes
Исправляй

2017-05-13 18:48 UTC, evgenyrodionov commented on src/ShoesCategory/Content/Badge.js
> +import React from 'react';
Почему два разных стиля написания? В одном делаешь => (), в другой => { return () }

2017-05-13 18:48 UTC, evgenyrodionov commented on src/ShoesCategory/Content/Card.js
> +import React from 'react';
Тоже

2017-05-13 18:48 UTC, evgenyrodionov commented on src/ShoesCategory/index.js
> +    <Router>
Это должно быть в апп.джс

2017-05-13 18:48 UTC, evgenyrodionov commented on src/ShoesCategory/index.js
> +import Details from './Content/Details';
Правила импортов в телеграфе

2017-05-13 18:48 UTC, evgenyrodionov commented
К слову, что такое ShoesCategory?

2017-05-13 18:48 UTC, evgenyrodionov commented
В телеграфе есть правила архитектуры

2017-05-13 19:01 UTC, pbuzdin commented
Так а с роутером что? как передать класс active когда навлинк находится внутри другого компонента?

2017-05-13 20:56 UTC, pbuzdin commented
Исправил, только про импорт не понял. Что с ним не так?

2017-05-13 23:06 UTC, imevro approved these changes
Норм, но ↓

Смерджу после интеграции с трэвисом и зеленым билдом

2017-05-13 23:06 UTC, evgenyrodionov commented on package.json
> +    "lint": "(npm bin)/eslint src",
Доллар верни

2017-05-13 23:06 UTC, evgenyrodionov commented on src/App.js
> +        <NavLink to="/" className="category" activeClassName="active">shoes</NavLink>
Зачем этот мусор тут?

2017-05-13 23:07 UTC, evgenyrodionov commented
А, стоп, нихуя не норм. Я же сказал про архитектуру прочитать, почему у тебя до сих пор Catalog? Почему SelectGender и SelectSize вместе с Card.js, если они относятся к фильтру?

2017-05-13 23:07 UTC, imevro requested changes
Фикси архитектуру

2017-05-14 01:49 UTC, pbuzdin commented
Все вылечил

2017-05-14 09:48 UTC, evgenyrodionov commented
![image](https://cloud.githubusercontent.com/assets/775692/26032755/ab5ecf5c-38a3-11e7-91f7-196d81451e57.png)

2017-05-14 09:49 UTC, imevro requested changes
Архитектура

2017-05-14 10:51 UTC, pbuzdin commented
@evgenyrodionov пофиксил

2017-05-14 13:53 UTC, imevro approved these changes
Норм

2017-05-14 13:53 UTC, merged